apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etlegacy-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust size as needed
  storageClassName: do-block-storage
