apiVersion: v1
kind: PersistentVolume
metadata:
  name: etlegacy-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/etdata/etlegacy  # Local filesystem path


