apiVersion: v1
kind: Service
metadata:
  name: etlegacy-service
  labels:
    app: etlegacy
spec:
  type: NodePort
  selector:
    app: etlegacy
  ports:
    - protocol: UDP
      port: 27960
      targetPort: 27960
      nodePort: 30080
