apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etlegacy-deployment
spec:
  template:
    spec:
      volumes:
      - name: etlegacy-storage
        hostPath:
          path: /opt/data/etlegacy  # Local filesystem path
          type: DirectoryOrCreate
  volumeClaimTemplates:
  - metadata:
      name: etlegacy-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: hostpath  # StorageClass name
